### ISSUE TITLE
Dscan.me shutting down

### ISSUE THREAD

**Issue by luffe0601** [devfleet/awesome-eve#122]
[dscan](http://dscan.me/)

`Pilots, the time has come for me to say goodbye.
I quit playing EVE a couple of years ago but kept this site alive due to its relative (and surprising, to me) popularity and its value as one of the only truly neutral dscan tools. This cost me a not-insigificant amount of money, however it was still a useful learning tool for me. Unfortunately I have moved on to other (paying) projects which serve the same purpose. As such this site only serves to consume my time whenever something goes wrong and my money continuously for something I am no longer interested in.

I thank you all for your interest in the site over the years. It was fun to work on and a valuable learning tool working on real world loads and data. If the sites closure disrupts your tools or workflow, I apologise, but I think its better to simply close the site down than to keep it in this limbo of on-again-off-again functioning. I think the responsible thing to do is shut it down.

What will happen to the site from here? I will probably keep the domain registered for the next year at least to prevent nefarious actors somehow using it to attack your tools or leech off the good faith this site built over the years. No EVE intel was ever shared with any third party and I am proud of that. I did have a suggestion that I open source or pass the site on to another person to take over. While I certainly like the idea, I have no way of vetting the person taking over to ensure they maintain the privacy oriented approach that I followed. As for open source, its possible but the site was never written with other operators in mind I don't think it would be particularly useful and I'm not convinced that open sourcing it would actually reduce the amount of attention I would need to give the codebase. But if you think we could work something out, feel free to email me: deannaskanna@gmail.com

Thank you all and fly safe o7
`

**Comment by luffe0601** [comment]
evewarfare.com look like is down

**Comment by luffe0601** [comment]
[Utils Space](https://utils.space/killmails/) this one ,when i open it on my chrome: `NET::ERR_CERT_AUTHORITY_INVALID`, and i try to use http, and i see: `default backend - 404`.

**Comment by cvweiss** [comment]
The proper way to do this is not to open issues but to create Pull Requests.
