### ISSUE TITLE
Eve Overview Manager

### ISSUE THREAD

**Issue by ASB2** [devfleet/awesome-eve#133]
https://github.com/Bertral/EANM

**Comment by GoldenGnu** [comment]
The proper way to do this is not to open issues but to create Pull Requests.

from the README.md:
> * Create a Pull Request with the name of your tool, the URL (or app name) of your tool, a category it should go into, and a very brief description of what it does.
> * Your product should be user friendly and beyond "beta" stages.
> * If approved, it will be added! Yay!
