### ISSUE TITLE
LMeve

### ISSUE THREAD

**Issue by roxlukas** [devfleet/awesome-eve#21]
LMeve industry and corp tracker. WebGL 3D Killboard included.

https://github.com/roxlukas/lmeve

Thanks!

**Comment by cvweiss** [comment]
Hi, I'm a bit reluctant to add this since the author is taking a break from Eve Online and he even states in the repo that the code isn't meant for production use and all tags are marked as beta. @fuzzysteve or @Regner, what do you think?

**Comment by cvweiss** [comment]
Do you have any other suggestions?

**Comment by roxlukas** [comment]
It seems only truly awesome EVE apps are on this list. Keep up good work and tight selection then :-)

**Comment by Regner** [comment]
LMEve releases tend to be pretty stable. Been a while since I ran it but back then it was pretty solid.
