### ISSUE TITLE
Add evemon to the list

### ISSUE THREAD

**Issue by CrenshawCoding** [devfleet/awesome-eve#216]
This seems to be the currently maintained version of evemon: https://github.com/mgoeppner/evemon.

It's a skill planning tool

**Comment by cvweiss** [comment]
Did you mean to create a PR?

Besides OP, who can attest that EveMon is actively maintained?

**Comment by joaomlneto** [comment]
I've installed `mgoeppner/evemon` on a windows VM a few months ago: it works with current ESI and was updated soon after the Viridian SDE was released, but personally don't use it extensively (as an 🍎🍔📖 user) nor have audited the codebase.

It does seem to be the only EVEMon fork being updated regularly, being also the [most starred, excluding the original `peterhaneve/evemon` repository](https://github.com/peterhaneve/evemon/forks?include=active&page=1&period=2y&sort_by=stargazer_counts) and [most recently updated](https://github.com/peterhaneve/evemon/forks?include=active&page=1&period=2y&sort_by=last_updated).

[InfinitasX](https://forums.eveonline.com/u/infinitasx) (I assume who is behind the fork) has made the effort to maintain it for quite some time, as indicated by [his posting history](https://forums.eveonline.com/u/infinitasx/activity).

Hopefully someone else will confirm/refute what I said above. :)
