### ISSUE TITLE
Pathfinder

### ISSUE THREAD

**Issue by ScotDex** [devfleet/awesome-eve#218]
https://pathfinder-eve.space/

I have cloned the original pathfinder and currently maintain it for public use.

I have absolutely no involvement in the development or creation of the original tool and take no credit for that

Your current URL is dead due to original creator abandoning the project.

Thought this may be useful for you <3

Dex

**Comment by cvweiss** [comment]
If the project is dead it should be removed. Thank you for letting me know.
