### ISSUE TITLE
EVE API "scoreboard" to show coverage among ESI, XML API, CREST

### ISSUE THREAD

**Issue by deadlybulb** [devfleet/awesome-eve#30]
Thinking we should start maintaining a scoreboard for how much functionality has moved from the XML API (or CREST) to the ESI.  We could maintain that here, or we could put it on http://eveonline-third-party-documentation.readthedocs.io/en/latest/index.html although that site may not be getting much traffic now that ESI is out.

I'm assuming CCP hasn't been maintaining this information anywhere (or rather, I couldn't find it).

Thoughts?

**Comment by cvweiss** [comment]
I like the idea, I just don't want to have to maintain the scores lol

**Comment by biow0lf** [comment]
Ok, lets start this list https://github.com/biow0lf/eveonline-xml-vs-crest-vs-esi :)

**Comment by deadlybulb** [comment]
Should we just link that or copy over?  Once we have a home for it, I can start submitting PRs.

**Comment by cvweiss** [comment]
I'd say link it, we can have our own small table with approximate percentage points while the meat of it is on @biow0lf 's site. What do you think?

**Comment by deadlybulb** [comment]
SGTM.

**Comment by cvweiss** [comment]
I don't see much activity happening on https://github.com/biow0lf/eveonline-xml-vs-crest-vs-esi , has this been forgotten?

**Comment by deadlybulb** [comment]
I haven't forgotten.  Just been busy.

**Comment by deadlybulb** [comment]
No longer relevant thanks to:

https://github.com/ccpgames/esi-issues/blob/master/XML_to_ESI.md
