### ISSUE TITLE
EVEpoll

### ISSUE THREAD

**Issue by snitchashor** [devfleet/awesome-eve#38]
https://evepoll.tk might be added.

Descriprion would be "Create polls for your corp, alliance or the EVE universe."

If you need a feature list:

SSO to authenticate
Create polls, available to your corp, alliance or anyone
Define the duration for your poll(s)
Select whether initial choices can be changed
Select whether or not the result is visible before the poll ends (owners will always see it)
Select if more than one vote is allowed per IP address
End your poll at any time
Delete your poll(s) (Yes, they are removed completely)
Browse polls available to your corp or alliance
Mobile friendly

Cheers,
Snitch

**Comment by cvweiss** [comment]
> evepoll.tk’s server DNS address could not be found.

**Comment by snitchashor** [comment]
Just checked, should have been up and was used the last 2 days. I can give you the IP but you still have to access by the FQDN for SSO to work...

**Comment by cvweiss** [comment]
Yea, it was an issue with DNS where I work. Can you create a pull request for this please?

**Comment by snitchashor** [comment]
Sure will do on monday. Only got a mobile right now.
