### ISSUE TITLE
New Programs

### ISSUE THREAD

**Issue by drkthunder02** [devfleet/awesome-eve#48]
[EVE OTS V2](https://github.com/drkthunder02/eveotsv2)

EVE Online TeamSpeak Authentication v2 utilizes ESI authentication to authenticate a user for Teamspeak.  Replaces EVEOTS

[Stand-Alone PHP Timerboard](https://github.com/drkthunder02/phptimerboard)

Stand Alone PHP Timerboard.  Work in progress.

**Comment by cvweiss** [comment]
Please recreate this as a Pull Request with the appropriate changes. Thank you!
