### ISSUE TITLE
Eve chat notification

### ISSUE THREAD

**Issue by MyUncleSam** [devfleet/awesome-eve#55]
Hi there,

I love this list and wanted to tell you I wrote a program for chat notification. Would be great if you add it to your list.

Git: https://github.com/MyUncleSam/EveChatNotifier

**Comment by cvweiss** [comment]
Wow, this looks useful! All you need to do is create a PR 👍

**Comment by MyUncleSam** [comment]
what do you mean with "PR"?

**Comment by cvweiss** [comment]
https://help.github.com/articles/creating-a-pull-request/

**Comment by cvweiss** [comment]
#56 

Thanks!
