### ISSUE TITLE
Splitting the single list to 2 sections

### ISSUE THREAD

**Issue by Phrynohyas** [devfleet/awesome-eve#6]
> Squizz Caphinator
> 
> While I see some merit in your suggestion, I think it would be better kept as a single list. Maybe some of the other maintainers might have a different idea, maybe create an issue where we can discuss it?

The suggestion was to split the list into 2 sections in the same document:

1st with the list of lets call it 'customer tools' - end user tools for players
2nd with the list of software developer stuff like API libraries and so on. While they are really awesome 90% of players don't need it (and are not interested on it)

**Comment by deadlybulb** [comment]
Sounds reasonable to me.  You could then turn the second list into a table with columns indicating language support, etc.  The first list could likewise be characterized, perhaps around tool type (if there's a reasonable way to categorize).

If I have some time later I'll work on  a PR with the more complicated split.  For now, maybe just the simple split here is good enough.

**Comment by GoldenGnu** [comment]
I agree with splitting the list in two. I also want to see a category for libraries in the developer list, preferably with sup categories for each language.

**Comment by cvweiss** [comment]
Is anyone going to PR this list split?
