### ISSUE TITLE
EveSkillboard, EveStructures

### ISSUE THREAD

**Issue by skiedude** [devfleet/awesome-eve#64]
Ahoy,

I'd like to add the following sites:
https://eveskillboard.com
https://structures.eveskillboard.com

I've created a local branch with my changes, but not allowed to push it to create a PR. 

Lemme know!

**Comment by cvweiss** [comment]
Create the pull request and I'll be happy to accept. If you're not sure how this might help:

https://help.github.com/articles/creating-a-pull-request/
