### ISSUE TITLE
evescoutrescue.com

### ISSUE THREAD

**Issue by Thricehappy** [devfleet/awesome-eve#86]
New Eden's Premier Wormhole Rescue Service

The EvE-Scout Rescue Cache (ESRC) program provides a basic emergency resource kit for capsuleers stranded in wormholes. In situations where no rescue cache is present, the EvE-Scout Search and Rescue (SAR) program strives to facilitate a live rescue by one of our scouts.

These services are offered to all pilots, regardless of alliance, sovereignty, or play style.

**Comment by cvweiss** [comment]
awesome-eve isn't really an advertising service, but if you create a PR with a link to your website and short blurb of what you do that will be fine. Probably be best to create a small Public Services section
